import 'package:flutter/material.dart';
import 'package:tcc_app/models/extended_color_model.dart';
import 'package:tcc_app/themes/extended_theme.dart';

class MaterialTheme {
  final TextTheme textTheme;

  const MaterialTheme(this.textTheme);

  static ColorScheme lightScheme() => const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff6a4cab),
    surfaceTint: Color(0xff6a4cab),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffb99aff),
    onPrimaryContainer: Color(0xff4a2b89),
    secondary: Color(0xff64587f),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffe0d0fd),
    onSecondaryContainer: Color(0xff63577e),
    tertiary: Color(0xff525f75),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffd6e3fe),
    onTertiaryContainer: Color(0xff58657c),
    error: Color(0xffb41c1b),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffd83831),
    onErrorContainer: Color(0xfffffbff),
    surface: Color(0xfffef7ff),
    onSurface: Color(0xff1d1a21),
    onSurfaceVariant: Color(0xff494551),
    outline: Color(0xff7a7582),
    outlineVariant: Color(0xffcbc4d3),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff322f36),
    inversePrimary: Color(0xffd1bcff),
    primaryFixed: Color(0xffeaddff),
    onPrimaryFixed: Color(0xff24005b),
    primaryFixedDim: Color(0xffd1bcff),
    onPrimaryFixedVariant: Color(0xff523391),
    secondaryFixed: Color(0xffeaddff),
    onSecondaryFixed: Color(0xff201538),
    secondaryFixedDim: Color(0xffcfbfec),
    onSecondaryFixedVariant: Color(0xff4c4166),
    tertiaryFixed: Color(0xffd6e3fe),
    onTertiaryFixed: Color(0xff0f1c2f),
    tertiaryFixedDim: Color(0xffbac7e1),
    onTertiaryFixedVariant: Color(0xff3b475d),
    surfaceDim: Color(0xffded8e1),
    surfaceBright: Color(0xfffef7ff),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff8f1fa),
    surfaceContainer: Color(0xfff2ecf5),
    surfaceContainerHigh: Color(0xffece6ef),
    surfaceContainerHighest: Color(0xffe7e0e9),
  );

  ThemeData light() => theme(lightScheme());

  static ColorScheme lightMediumContrastScheme() => const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff412080),
    surfaceTint: Color(0xff6a4cab),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xff795cbb),
    onPrimaryContainer: Color(0xffffffff),
    secondary: Color(0xff3b3054),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xff73678e),
    onSecondaryContainer: Color(0xffffffff),
    tertiary: Color(0xff2a374b),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xff616e85),
    onTertiaryContainer: Color(0xffffffff),
    error: Color(0xff740006),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffcd302a),
    onErrorContainer: Color(0xffffffff),
    surface: Color(0xfffef7ff),
    onSurface: Color(0xff121016),
    onSurfaceVariant: Color(0xff383440),
    outline: Color(0xff55505d),
    outlineVariant: Color(0xff706b78),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff322f36),
    inversePrimary: Color(0xffd1bcff),
    primaryFixed: Color(0xff795cbb),
    onPrimaryFixed: Color(0xffffffff),
    primaryFixedDim: Color(0xff6042a1),
    onPrimaryFixedVariant: Color(0xffffffff),
    secondaryFixed: Color(0xff73678e),
    onSecondaryFixed: Color(0xffffffff),
    secondaryFixedDim: Color(0xff5a4f75),
    onSecondaryFixedVariant: Color(0xffffffff),
    tertiaryFixed: Color(0xff616e85),
    onTertiaryFixed: Color(0xffffffff),
    tertiaryFixedDim: Color(0xff49556b),
    onTertiaryFixedVariant: Color(0xffffffff),
    surfaceDim: Color(0xffcac4cd),
    surfaceBright: Color(0xfffef7ff),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff8f1fa),
    surfaceContainer: Color(0xffece6ef),
    surfaceContainerHigh: Color(0xffe1dbe4),
    surfaceContainerHighest: Color(0xffd6d0d8),
  );

  ThemeData lightMediumContrast() => theme(lightMediumContrastScheme());

  static ColorScheme lightHighContrastScheme() => const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff361275),
    surfaceTint: Color(0xff6a4cab),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xff543694),
    onPrimaryContainer: Color(0xffffffff),
    secondary: Color(0xff312649),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xff4f4368),
    onSecondaryContainer: Color(0xffffffff),
    tertiary: Color(0xff202c41),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xff3d4a5f),
    onTertiaryContainer: Color(0xffffffff),
    error: Color(0xff600004),
    onError: Color(0xffffffff),
    errorContainer: Color(0xff98000b),
    onErrorContainer: Color(0xffffffff),
    surface: Color(0xfffef7ff),
    onSurface: Color(0xff000000),
    onSurfaceVariant: Color(0xff000000),
    outline: Color(0xff2e2a36),
    outlineVariant: Color(0xff4c4754),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff322f36),
    inversePrimary: Color(0xffd1bcff),
    primaryFixed: Color(0xff543694),
    onPrimaryFixed: Color(0xffffffff),
    primaryFixedDim: Color(0xff3d1c7c),
    onPrimaryFixedVariant: Color(0xffffffff),
    secondaryFixed: Color(0xff4f4368),
    onSecondaryFixed: Color(0xffffffff),
    secondaryFixedDim: Color(0xff382d50),
    onSecondaryFixedVariant: Color(0xffffffff),
    tertiaryFixed: Color(0xff3d4a5f),
    onTertiaryFixed: Color(0xffffffff),
    tertiaryFixedDim: Color(0xff263348),
    onTertiaryFixedVariant: Color(0xffffffff),
    surfaceDim: Color(0xffbcb7bf),
    surfaceBright: Color(0xfffef7ff),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff5eef8),
    surfaceContainer: Color(0xffe7e0e9),
    surfaceContainerHigh: Color(0xffd8d2db),
    surfaceContainerHighest: Color(0xffcac4cd),
  );

  ThemeData lightHighContrast() => theme(lightHighContrastScheme());

  static ColorScheme darkScheme() => const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xffd1bcff),
    surfaceTint: Color(0xffd1bcff),
    onPrimary: Color(0xff3b187a),
    primaryContainer: Color(0xffb99aff),
    onPrimaryContainer: Color(0xff4a2b89),
    secondary: Color(0xffcfbfec),
    onSecondary: Color(0xff352a4e),
    secondaryContainer: Color(0xff4e4368),
    onSecondaryContainer: Color(0xffc0b1dd),
    tertiary: Color(0xffffffff),
    onTertiary: Color(0xff243145),
    tertiaryContainer: Color(0xffd6e3fe),
    onTertiaryContainer: Color(0xff58657c),
    error: Color(0xffffb4ab),
    onError: Color(0xff690005),
    errorContainer: Color(0xffff5449),
    onErrorContainer: Color(0xff5c0004),
    surface: Color(0xff141218),
    onSurface: Color(0xffe7e0e9),
    onSurfaceVariant: Color(0xffcbc4d3),
    outline: Color(0xff948e9c),
    outlineVariant: Color(0xff494551),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffe7e0e9),
    inversePrimary: Color(0xff6a4cab),
    primaryFixed: Color(0xffeaddff),
    onPrimaryFixed: Color(0xff24005b),
    primaryFixedDim: Color(0xffd1bcff),
    onPrimaryFixedVariant: Color(0xff523391),
    secondaryFixed: Color(0xffeaddff),
    onSecondaryFixed: Color(0xff201538),
    secondaryFixedDim: Color(0xffcfbfec),
    onSecondaryFixedVariant: Color(0xff4c4166),
    tertiaryFixed: Color(0xffd6e3fe),
    onTertiaryFixed: Color(0xff0f1c2f),
    tertiaryFixedDim: Color(0xffbac7e1),
    onTertiaryFixedVariant: Color(0xff3b475d),
    surfaceDim: Color(0xff141218),
    surfaceBright: Color(0xff3b383f),
    surfaceContainerLowest: Color(0xff0f0d13),
    surfaceContainerLow: Color(0xff1d1a21),
    surfaceContainer: Color(0xff211e25),
    surfaceContainerHigh: Color(0xff2b292f),
    surfaceContainerHighest: Color(0xff36343a),
  );

  ThemeData dark() => theme(darkScheme());

  static ColorScheme darkMediumContrastScheme() => const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xffe4d6ff),
    surfaceTint: Color(0xffd1bcff),
    onPrimary: Color(0xff2f066f),
    primaryContainer: Color(0xffb99aff),
    onPrimaryContainer: Color(0xff2a0067),
    secondary: Color(0xffe4d6ff),
    onSecondary: Color(0xff2a1f42),
    secondaryContainer: Color(0xff988ab4),
    onSecondaryContainer: Color(0xff000000),
    tertiary: Color(0xffffffff),
    onTertiary: Color(0xff243145),
    tertiaryContainer: Color(0xffd6e3fe),
    onTertiaryContainer: Color(0xff3c485e),
    error: Color(0xffffd2cc),
    onError: Color(0xff540003),
    errorContainer: Color(0xffff5449),
    onErrorContainer: Color(0xff000000),
    surface: Color(0xff141218),
    onSurface: Color(0xffffffff),
    onSurfaceVariant: Color(0xffe1d9e9),
    outline: Color(0xffb6afbe),
    outlineVariant: Color(0xff948e9c),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffe7e0e9),
    inversePrimary: Color(0xff533593),
    primaryFixed: Color(0xffeaddff),
    onPrimaryFixed: Color(0xff170041),
    primaryFixedDim: Color(0xffd1bcff),
    onPrimaryFixedVariant: Color(0xff412080),
    secondaryFixed: Color(0xffeaddff),
    onSecondaryFixed: Color(0xff150a2d),
    secondaryFixedDim: Color(0xffcfbfec),
    onSecondaryFixedVariant: Color(0xff3b3054),
    tertiaryFixed: Color(0xffd6e3fe),
    onTertiaryFixed: Color(0xff041124),
    tertiaryFixedDim: Color(0xffbac7e1),
    onTertiaryFixedVariant: Color(0xff2a374b),
    surfaceDim: Color(0xff141218),
    surfaceBright: Color(0xff46434a),
    surfaceContainerLowest: Color(0xff08070c),
    surfaceContainerLow: Color(0xff1f1c23),
    surfaceContainer: Color(0xff29272d),
    surfaceContainerHigh: Color(0xff343138),
    surfaceContainerHighest: Color(0xff3f3c43),
  );

  ThemeData darkMediumContrast() => theme(darkMediumContrastScheme());

  static ColorScheme darkHighContrastScheme() => const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xfff6ecff),
    surfaceTint: Color(0xffd1bcff),
    onPrimary: Color(0xff000000),
    primaryContainer: Color(0xffceb7ff),
    onPrimaryContainer: Color(0xff100032),
    secondary: Color(0xfff6ecff),
    onSecondary: Color(0xff000000),
    secondaryContainer: Color(0xffcbbce8),
    onSecondaryContainer: Color(0xff0f0427),
    tertiary: Color(0xffffffff),
    onTertiary: Color(0xff000000),
    tertiaryContainer: Color(0xffd6e3fe),
    onTertiaryContainer: Color(0xff1e2a3f),
    error: Color(0xffffece9),
    onError: Color(0xff000000),
    errorContainer: Color(0xffffaea5),
    onErrorContainer: Color(0xff220001),
    surface: Color(0xff141218),
    onSurface: Color(0xffffffff),
    onSurfaceVariant: Color(0xffffffff),
    outline: Color(0xfff5edfd),
    outlineVariant: Color(0xffc7c0cf),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffe7e0e9),
    inversePrimary: Color(0xff533593),
    primaryFixed: Color(0xffeaddff),
    onPrimaryFixed: Color(0xff000000),
    primaryFixedDim: Color(0xffd1bcff),
    onPrimaryFixedVariant: Color(0xff170041),
    secondaryFixed: Color(0xffeaddff),
    onSecondaryFixed: Color(0xff000000),
    secondaryFixedDim: Color(0xffcfbfec),
    onSecondaryFixedVariant: Color(0xff150a2d),
    tertiaryFixed: Color(0xffd6e3fe),
    onTertiaryFixed: Color(0xff000000),
    tertiaryFixedDim: Color(0xffbac7e1),
    onTertiaryFixedVariant: Color(0xff041124),
    surfaceDim: Color(0xff141218),
    surfaceBright: Color(0xff524f56),
    surfaceContainerLowest: Color(0xff000000),
    surfaceContainerLow: Color(0xff211e25),
    surfaceContainer: Color(0xff322f36),
    surfaceContainerHigh: Color(0xff3d3a41),
    surfaceContainerHighest: Color(0xff49454d),
  );

  ThemeData darkHighContrast() => theme(darkHighContrastScheme());

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
    useMaterial3: true,
    brightness: colorScheme.brightness,
    colorScheme: colorScheme,
    textTheme: textTheme.apply(
      bodyColor: colorScheme.onSurface,
      displayColor: colorScheme.onSurface,
    ),
    scaffoldBackgroundColor: colorScheme.surface,
    canvasColor: colorScheme.surface,
  );

  List<ExtendedColor> get extendedColors => [success, warning];
}
